version: "3.6"

services:
  kinesis:
    image: leprechaun/kinesalite
    ports:
      - 4567:4567
  pg:
    image: postgres:11
    environment:
      POSTGRES_USER: snacker-tracker-reporter
      POSTGRES_PASSWORD: super-secure
      POSTGRES_DB: snacker-tracker-reporter-default
    ports:
      - 5432:5432
    volumes:
      - ./backup/:/mnt/backups/

  pgtest:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: snacker-tracker-reporter
      POSTGRES_PASSWORD: super-secure

  bare: &bare
    image: node:10
    working_dir: /app/
    command: yarn dev
    volumes:
      - ./:/app/
      - yarn-cache:/usr/local/share/.cache/yarn/v2
      - node_modules:/app/node_modules/
    environment:
      APP_VERSION: 0.1.0-snapshot
      ENVIRONMENT_NAME: default
      USE_SWAGGER_VALIDATION: "true"
      DEBUG: knex:query
      PORT: 5000
      DATABASE_HOST: ${DATABASE_HOST-pg}
      DATABASE_NAME: ${DATABASE_NAME-snacker-tracker-reporter-default}
      DATABASE_USERNAME: ${DATABASE_USERNAME-snacker-tracker-reporter}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD-super-secure}
      AWS_ACCESS_KEY: empty
      AWS_SECRET_ACCESS_KEY: empty
      KINESIS_ENDPOINT: http://kinesis:4567/
      KINESIS_STREAM: snack-stream

  full:
    <<: *bare
    ports:
      - 5000:5000
    depends_on:
      - pg
      - kinesis

volumes:
  node_modules: {}
  yarn-cache: {
    external: true
  }
