apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snacker-tracker-recorder.fullname" . }}
  labels:
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
{{ include "snacker-tracker-recorder.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "snacker-tracker-recorder.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "snacker-tracker-recorder.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
      annotations:
        prometheus.io/port: "{{ .Values.service.internal_port }}"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internal_port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health?probe=liveness
              port: http
          readinessProbe:
            httpGet:
              path: /health?probe=readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "snacker-tracker-recorder.fullname" . }}
            - secretRef:
                name: {{ include "snacker-tracker-recorder.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
